version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn store.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/app/static/
      - media:/app/media/
    expose:
      - 8000:8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - api

volumes:
  static:
  media:
